// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(TheTemptationDBContext))]
    partial class TheTemptationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Model.Draw", b =>
                {
                    b.Property<int>("IdDraw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDraw"));

                    b.Property<DateTime>("DateHourDraw")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameWin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jackpot")
                        .HasColumnType("int");

                    b.HasKey("IdDraw");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("DataLayer.Model.GameUser", b =>
                {
                    b.Property<string>("CodeShortGui")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DrawIdDraw")
                        .HasColumnType("int");

                    b.Property<string>("GamePlaying")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDraw")
                        .HasColumnType("int");

                    b.HasKey("CodeShortGui");

                    b.HasIndex("DrawIdDraw");

                    b.ToTable("GameUsers");
                });

            modelBuilder.Entity("DataLayer.Model.GameUser", b =>
                {
                    b.HasOne("DataLayer.Model.Draw", "Draw")
                        .WithMany("GameUsers")
                        .HasForeignKey("DrawIdDraw")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draw");
                });

            modelBuilder.Entity("DataLayer.Model.Draw", b =>
                {
                    b.Navigation("GameUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
